[package]
name = "polly"
version = "0.1.0"
authors = ["Aaronepower <theaaronepower@gmail.com>"]

[lib]
name = "polly"
path = "src/lib.rs"

[[bin]]
name = "polly"
path = "src/main.rs"

[dependencies]
clap = {version = "*", features = ["yaml"]}
serde = "*"
serde_json = "*"
lazy_static = "*"